# syntax=docker/dockerfile:1

FROM balenalib/raspberry-pi-python:3.8

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN apt-get update && apt-get install python3-dev gcc libc-dev libffi-dev
RUN pip install pipenv
RUN pip install gunicorn 
RUN pipenv install --system --deploy

CMD [ "gunicorn", "api:app", "-w", "2", "--threads", "2", "-b", "0.0.0.0:6000", "--error-logfile", "payapp_output.log", "--preload"]
